- name: play1
  hosts: all
  tasks:
   - name: print my designation from tast1 of play1
     ansible.builtin.debug:
           msg: data cenyter expert from tast1 of play1

 - name: Play1 
  hosts: all 
  tasks:
    - name: Print Hello from task1 of play1 
      ansible.builtin.debug:
            msg: Hai from task1 of play1 

    - name: Print Hello from task2 of play1 
      ansible.builtin.debug:
            msg: Hai from task2 of play1 

- name: Play2
  hosts: dev 
  tasks:
    - name: Print Hello from task2 of play1 
      ansible.builtin.debug:
            msg: Hai from dev task1 of play2
          