- name: Demo on facts 
  hosts: all 
  tasks:
    - name: Print uptime sec 
      ansible.builtin.debug: 
        msg: printing uptime {{ansible_uptime_seconds}}  
    
    - name: Printing Mac Address 
      ansible.builtin.debug:
        msg: Mac Address is {{ansible_default_ipv4.macaddress}}




     