- name: Demo on using shell module 
  hosts: all 
  tasks: 
    - name: Running a shell commands 
      ansible.builtin.shell: df -h
      register: diskinv

    - name: Printing the diskinv variable 
      ansible.builtin.debug: 
        msg: "{{diskinv}}"

