- name: Demo on using shell module 
  hosts: all
  tasks:
    - name: running a shell Command
      ansible.builtin.shell: df -h
      register: diskinv

    - name: printing the diskinv variable
      ansible.builtin.debug
        msg: printing df -h {{diskinv}}  
